package com.example.demo.mapper;

import java.util.List;
import java.util.Map;

import com.example.demo.entity.Foods;

public interface FoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    int deleteByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    int insert(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    int insertSelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    Foods selectByPrimaryKey(Integer foodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    int updateByPrimaryKeySelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_foods
     *
     * @mbggenerated Wed May 09 16:55:28 CST 2018
     */
    int updateByPrimaryKey(Foods record);

	List<Foods> getFoodList(Map<String, Object> map);

	Integer selectFoodsCount();
}